pool:
  vmImage: ubuntu-16.04
trigger:
  - master
steps:
  - task: Npm@1
    inputs:
      command: install
    continueOnError: true
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: $(System.DefaultWorkingDirectory)/test-report.xml
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish Code Coverage'
    condition: 'in(variables[''Agent.JobStatus''], ''Succeeded'')'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/*coverage.xml'
      reportDirectory: $(System.DefaultWorkingDirectory)/coverage
  - task: ArchiveFiles@2
    displayName: 'Archive sources'
    inputs:
      rootFolderOrFile: $(Build.SourcesDirectory)
      includeRootFolder: false
  - task: CopyFiles@2
    displayName: 'Copy ARM templates'
    inputs:
      SourceFolder: deployment
      Contents: '*.json'
      TargetFolder: $(build.artifactstagingdirectory)/Templates
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
  - task: FortifyOnDemandStatic@5
    inputs:
      FortifyProjects: '$(build.artifactstagingdirectory)'
      BSIToken: 'eyJ0ZW5hbnRJZCI6NSwidGVuYW50Q29kZSI6InR0MSIsInJlbGVhc2VJZCI6MTU5NjAsInBheWxvYWRUeXBlIjoiQU5BTFlTSVNfUEFZTE9BRCIsImFzc2Vzc21lbnRUeXBlSWQiOjExOSwidGVjaG5vbG9neVR5cGUiOiJKUy9UUy9IVE1MIiwidGVjaG5vbG9neVR5cGVJZCI6MTYsInRlY2hub2xvZ3lWZXJzaW9uIjpudWxsLCJ0ZWNobm9sb2d5VmVyc2lvbklkIjpudWxsLCJhdWRpdFByZWZlcmVuY2UiOiJBdXRvbWF0ZWQiLCJhdWRpdFByZWZlcmVuY2VJZCI6MiwiaW5jbHVkZVRoaXJkUGFydHkiOmZhbHNlLCJpbmNsdWRlT3BlblNvdXJjZUFuYWx5c2lzIjpmYWxzZSwicG9ydGFsVXJpIjoiaHR0cHM6Ly9mb2RxYTktdGVuYW50LmZvcnRpZnlmb2RxYTkubG9jYWwiLCJhcGlVcmkiOiJodHRwOi8vMTYuMTAzLjIzNC4yMzciLCJzY2FuUHJlZmVyZW5jZSI6IlN0YW5kYXJkIiwic2NhblByZWZlcmVuY2VJZCI6MX0='
      APIAuthenticationType: '2'
      Username: 'eric_security_lead'
      PersonalAccessTokenSecret: 'S0EjXUV0ImxvaFN2aDBVY0dOWmh5algyMHJ2MFUw0'
      TenantID: 'TT1'
      EntitlementPreference: '1'
      PurchaseEntitlements: false
      InProgressScanActionType: '0'
      RemediationScanPreference: '0'
      PolicyFailAction: '1'